---

- hosts: all
  become_user: root
  tasks:

  - name: update repository index
    yum: 
      update_cache: yes

  - name: install apache2 package
    yum:
      name: httpd
      state: latest

  - name: php support for apache
    yum: 
      name: php
      state: latest
