---

- hosts: all
  become_user: root
  tasks:

  - name: update repository index
    dnf: 
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "Rocky"

  - name: php support for apache
    yum: 
      name: php
      state: latest
    when: ansible_distribution == "Rocky"

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
