---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum: 
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install apache2 package
    yum:
      name: httpd
      state: absent
    when: ansible_distribution == "Rocky"

  - name: php support for apache
    yum: 
      name: php
      state: absent
    when: ansible_distribution == "Rocky"
